name: yaps

ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - yaps
      - servant-client
      - warp >= 3.2.4
      - http-client
      - http-types
      - text
      - directory

library:
  source-dirs:
    - src

executables:
  yaps:
    main: exe/Main.hs
    dependencies:
      - yaps
      - safe

dependencies:
  - base
  - servant
  - servant-server
  - transformers
  - aeson
  - wai
  - warp
  - warp-tls
  - bytestring
  - text
  - cryptonite
  - directory
  - http-api-data
  - either
  - filepath
